stages:
  - tests

tests:
  stage: tests
  image: node:14
  script:
    - apt update && apt -y install git
    - npm install
    - npm run lint-js
    - npm run lint-css
  variables:
    VIARIBLE_TEST: test_value

