const MEMBERSHIP_CARD_IMAGE_TYPES = {
  HERO: 0,
  BANNER: 1,
  OFFER: 2,
  ICON: 3,
  ASSET: 4,
  REFERENCE: 5,
  PERSONAL_OFFERS: 6,
  PROMOTIONS: 7,
  TIER: 8,
  ALTERNATIVE: 9,
}

export { MEMBERSHIP_CARD_IMAGE_TYPES }

const MODAL_ACTION_TYPES = {
  PAYMENT_CARD_LIMIT: 'modals/PAYMENT_CARD_LIMIT',
  PAYMENT_CARD_ADD_FORM: 'modals/PAYMENT_CARD_ADD_FORM',
  PAYMENT_CARD_DELETE_FORM: 'modals/PAYMENT_CARD_DELETE_FORM',
  PAYMENT_CARD_LINKING_SUCCESS: 'modals/PAYMENT_CARD_LINKING_SUCCESS',
  PAYMENT_CARD_LINKING_ERROR: 'modals/PAYMENT_CARD_LINKING_ERROR',
  MEMBERSHIP_CARD_HERO: 'modals/MEMBERSHIP_CARD_HERO',
  MEMBERSHIP_CARD_TRANSACTIONS: 'modals/MEMBERSHIP_CARD_TRANSACTIONS',
  MEMBERSHIP_CARD_NO_TRANSACTIONS: 'modals/MEMBERSHIP_CARD_NO_TRANSACTIONS',
  MEMBERSHIP_CARD_NO_REWARDS: 'modals/MEMBERSHIP_CARD_NO_REWARDS',
  MEMBERSHIP_CARD_NON_ACTIVE_VOUCHERS: 'modals/MEMBERSHIP_CARD_NON_ACTIVE_VOUCHERS',
  MEMBERSHIP_CARD_DELETE: 'modals/MEMBERSHIP_CARD_DELETE',
  VOUCHER: 'modals/VOUCHER',
  ACCOUNT_MENU: 'modals/ACCOUNT_MENU',
  NO_MODAL: 'modals/NO_MODAL',
  MODAL_REQUEST: 'modals/MODAL_REQUEST',
}

export { MODAL_ACTION_TYPES }
