const MEMBERSHIP_CARD_IMAGE_TYPES = {
  HERO: 0,
  BANNER: 1,
  OFFER: 2,
  ICON: 3,
  ASSET: 4,
  REFERENCE: 5,
  PERSONAL_OFFERS: 6,
  PROMOTIONS: 7,
  TIER: 8,
  ALTERNATIVE: 9,
}

const MODAL_ACTION_TYPES = {
  PAYMENT_CARD_LIMIT: 'PAYMENT_CARD_LIMIT',
  PAYMENT_CARD_ADD_FORM: 'PAYMENT_CARD_ADD_FORM',
  PAYMENT_CARD_DELETE_FORM: 'PAYMENT_CARD_DELETE_FORM',
  PAYMENT_CARD_LINKING_SUCCESS: 'PAYMENT_CARD_LINKING_SUCCESS',
  PAYMENT_CARD_LINKING_ERROR: 'PAYMENT_CARD_LINKING_ERROR',
  MEMBERSHIP_CARD_HERO: 'MEMBERSHIP_CARD_HERO',
  MEMBERSHIP_CARD_TRANSACTIONS: 'MEMBERSHIP_CARD_TRANSACTIONS',
  MEMBERSHIP_CARD_NO_TRANSACTIONS: 'MEMBERSHIP_CARD_NO_TRANSACTIONS',
  MEMBERSHIP_CARD_NO_REWARDS: 'MEMBERSHIP_CARD_NO_REWARDS',
  MEMBERSHIP_CARD_NON_ACTIVE_VOUCHERS: 'MEMBERSHIP_CARD_NON_ACTIVE_VOUCHERS',
  MEMBERSHIP_CARD_DELETE: 'MEMBERSHIP_CARD_DELETE',
  VOUCHER: 'VOUCHER',
  ACCOUNT_MENU: 'ACCOUNT_MENU',
  NO_MODAL: 'NO_MODAL',
  MODAL_REQUEST: 'modals/MODAL_REQUEST',
}

const BARCODE_TYPES = {
  CODE128: 'code128',
  AZTEC_CODE: 'azteccode',
  PDF417: 'pdf417',
  EAN13: 'ean13',
  DATAMATRIX: 'datamatrix',
  ITF14: 'itf14',
  CODE39: 'code39',
  QR_CODE: 'qrcode',
}

export { MEMBERSHIP_CARD_IMAGE_TYPES, MODAL_ACTION_TYPES, BARCODE_TYPES }
